In [22]:
import joblib
import pandas as pd
import numpy as np
import json
from rdkit.Chem import MolFromSmiles
from rdkit.Chem import MACCSkeys

In [85]:
from rdkit.Chem import MolFromSmiles
from rdkit.Chem import MACCSkeys

In [109]:
from smiles_to_maccs import smiles_maccs

In [4]:
from sklearn.metrics import balanced_accuracy_score

In [4]:
rf_bal_best_save_reloaded = joblib.load( "best_rf_bal_model.pkl")

In [7]:
testX= pd.read_csv('testX.csv')
testy= pd.read_csv('testy.csv')


In [10]:
testX= testX.set_index('casrn')
testy= testy.set_index('casrn')

In [11]:
rf_bal_best_save_reloaded.predict(np.array(testX))

array([ True,  True,  True,  True,  True, False,  True, False,  True,
       False, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False, False,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False, False, False,  True,  True,
        True,  True, False,  True,  True,  True, False, False,  True,
       False,  True,  True,  True,  True, False,  True,  True, False,
        True,  True, False, False, False, False,  True,  True])

In [15]:
print(balanced_accuracy_score(np.array(testy), rf_bal_best_save_reloaded.predict(np.array(testX))))

0.8992914979757085


Test maccs generation method

In [5]:
# read SMILES files with maccs mapping
ames_maccs_smiles= pd.read_csv('ames_maccs_smiles_df.csv')

In [7]:
ames_maccs_smiles.Smiles[0]

'O=[N+]([O-])c1ccc(Cl)cc1'

In [137]:
ames_smiles_maccs_list= [smiles_maccs.smiles_maccs(smiles_input= smile_inst) for smile_inst in ames_maccs_smiles.Smiles]

In [138]:
pd.DataFrame(ames_smiles_maccs_list)

0
0    {"maccs_0":0,"maccs_1":0,"maccs_2":0,"maccs_3"...
1    {"maccs_0":0,"maccs_1":0,"maccs_2":0,"maccs_3"...
2    {"maccs_0":0,"maccs_1":0,"maccs_2":0,"maccs_3"...
3    {"maccs_0":0,"maccs_1":0,"maccs_2":0,"maccs_3"...
4    {"maccs_0":0,"maccs_1":0,"maccs_2":0,"maccs_3"...
..                                                 ...
699  {"maccs_0":0,"maccs_1":0,"maccs_2":0,"maccs_3"...
700  {"maccs_0":0,"maccs_1":0,"maccs_2":0,"maccs_3"...
701  {"maccs_0":0,"maccs_1":0,"maccs_2":0,"maccs_3"...
702  {"maccs_0":0,"maccs_1":0,"maccs_2":0,"maccs_3"...
703  {"maccs_0":0,"maccs_1":0,"maccs_2":0,"maccs_3"...

[704 rows x 1 columns]

In [110]:
smile_test_maccs= smiles_maccs.smiles_maccs(smiles_input= ames_maccs_smiles.Smiles[0])

In [111]:
smile_test_maccs

'{"maccs_0":0,"maccs_1":0,"maccs_2":0,"maccs_3":0,"maccs_4":0,"maccs_5":0,"maccs_6":0,"maccs_7":0,"maccs_8":0,"maccs_9":0,"maccs_10":0,"maccs_11":0,"maccs_12":0,"maccs_13":0,"maccs_14":0,"maccs_15":0,"maccs_16":0,"maccs_17":0,"maccs_18":0,"maccs_19":0,"maccs_20":0,"maccs_21":0,"maccs_22":0,"maccs_23":0,"maccs_24":1,"maccs_25":0,"maccs_26":0,"maccs_27":0,"maccs_28":0,"maccs_29":0,"maccs_30":0,"maccs_31":0,"maccs_32":0,"maccs_33":0,"maccs_34":0,"maccs_35":0,"maccs_36":0,"maccs_37":0,"maccs_38":0,"maccs_39":0,"maccs_40":0,"maccs_41":0,"maccs_42":0,"maccs_43":0,"maccs_44":0,"maccs_45":0,"maccs_46":0,"maccs_47":0,"maccs_48":0,"maccs_49":1,"maccs_50":0,"maccs_51":0,"maccs_52":0,"maccs_53":0,"maccs_54":0,"maccs_55":0,"maccs_56":1,"maccs_57":0,"maccs_58":0,"maccs_59":0,"maccs_60":0,"maccs_61":0,"maccs_62":0,"maccs_63":1,"maccs_64":0,"maccs_65":0,"maccs_66":0,"maccs_67":0,"maccs_68":0,"maccs_69":0,"maccs_70":1,"maccs_71":1,"maccs_72":0,"maccs_73":0,"maccs_74":0,"maccs_75":0,"maccs_76":0,"maccs_

In [130]:
# service test data
smile_test_maccs_dict= json.loads(smile_test_maccs)
del smile_test_maccs_dict['maccs_0']
test_maccs_array_service= np.array([True if val==1 else False for val in list(smile_test_maccs_dict.values()) ])


[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0]

In [123]:
# ames test data
test_maccs_array_ames= ames_maccs_smiles.iloc[:1,3:-1]
test_maccs_array_ames = np.array(test_maccs_array_ames)[0]

In [136]:
test_maccs_array_ames

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False, False, False, False, False, False,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False,  True,  True, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False,  True, False,  True, False, False,
       False, False,

In [135]:
# compare
test_maccs_array_service

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False, False, False, False, False, False,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False,  True,  True, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False,  True, False,  True, False, False,
       False, False,

In [115]:
test_maccs_array_ames

MACCSFP1  MACCSFP2  MACCSFP3  MACCSFP4  MACCSFP5  MACCSFP6  MACCSFP7  \
0     False     False     False     False     False     False     False   

   MACCSFP8  MACCSFP9  MACCSFP10  ...  MACCSFP157  MACCSFP158  MACCSFP159  \
0     False     False      False  ...       False        True        True   

   MACCSFP160  MACCSFP161  MACCSFP162  MACCSFP163  MACCSFP164  MACCSFP165  \
0       False        True        True        True        True        True   

   MACCSFP166  
0       False  

[1 rows x 166 columns]

In [74]:
test_maccs_array_service= np.array([True if val==1 else False for val in list(json.loads(smile_test_maccs).values()) ])

In [77]:
len(list(test_maccs_array_service))

167

In [97]:
mol= MolFromSmiles(ames_maccs_smiles.Smiles[0])
maccs_fp= MACCSkeys.GenMACCSKeys(mol)  # # get maccs fingerprints
maccs_fp_bits = list(maccs_fp) 

In [98]:
len(maccs_fp_bits)

167

In [101]:
list(range(166))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165]